/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/** Universal decode: decode from either an encoded image buffer (PNG/JPEG) or raw RGBA buffer. */
export declare function decode(data: Buffer, width?: number | undefined | null, height?: number | undefined | null, expectedVersion?: number | undefined | null): JsDecodeResult

/** Decode an RRC symbol directly from an encoded image file buffer (PNG, JPEG, WebP, etc.). */
export declare function decodeImage(imageBuffer: Buffer, expectedVersion?: number | undefined | null): JsDecodeResult

/** Decode an RRC symbol from an RGBA buffer (or compressed PNG/JPEG buffer). */
export declare function decodeRgba(rgba: Buffer, width: number, height: number, expectedVersion?: number | undefined | null): JsDecodeResult

/** Encode data into an RRC JPEG buffer. */
export declare function encodeJpeg(data: string | Buffer, options?: JsEncodeOptions | undefined | null): Buffer

/** Encode data into an RRC PNG buffer. */
export declare function encodePng(data: string | Buffer, options?: JsEncodeOptions | undefined | null): Buffer

/** Encode data into an RRC SVG string. */
export declare function encodeSvg(data: string | Buffer, options?: JsEncodeOptions | undefined | null): string

/** Get specifications and capacity metrics for a given RRC version. */
export declare function getVersionInfo(version: number): JsVersionInfo

export interface JsDecodeResult {
  payload: Buffer
  text?: string
  version: number
  eccLevel: string
  mode: string
}

export interface JsEncodeOptions {
  version?: number
  ecc?: string
  style?: string
  darkColor?: string
  lightColor?: string
  quietZone?: number
  renderScale?: number
  jpegQuality?: number
}

export interface JsVersionInfo {
  version: number
  ringCount: number
  totalDataBits: number
  totalCodewords: number
  capacityBytesM: number
}
